version: '3'
services:
  pydio:
    build: .
    volumes:
      - './.data/:/var/www/html'
    ports:
      - "8881:80"
      - "8090:8090"
    networks:
      - main
  mariadb:
    image: mariadb:latest
    environment:
      - 'MYSQL_ROOT_PASSWORD=test'
      - 'MYSQL_DATABASE=pydio'
    networks:
      - main
  postgres:
    image: postgres:latest
    environment:
      - 'POSTGRES_PASSWORD=test'
      - 'POSTGRES_DB=pydio'
    networks:
      - main
networks:
  main:
